
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 52
#define YY_END_OF_BUFFER 53
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[352] =
    {   0,
        0,    0,   53,   51,    4,    3,   51,   51,   43,   44,
       42,   51,   51,   51,    8,    7,   41,   40,   51,   51,
       51,   47,   48,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   45,   46,   49,    0,   50,    0,
        0,    0,    0,   12,   11,    0,   15,    1,    2,   16,
        8,    0,    0,    8,    8,    0,    8,    7,    7,    7,
        7,    0,    0,    0,    0,    0,    0,    0,   37,   38,
       39,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   50,    0,    0,    0,    0,    0,    0,
        0,    0,    9,    0,    0,    0,    0,   12,   12,   12,

        0,   12,   11,   11,   11,   11,    0,   15,    2,    0,
       16,    0,   14,    8,    8,    8,    8,    0,    6,    7,
        7,    7,    7,    0,    0,    0,    0,    0,    0,    0,
        0,   26,    0,    0,    0,    0,    0,    0,    0,    0,
       50,    0,    0,    0,    0,    0,    0,   13,    0,    0,
       12,   12,   12,   12,   10,   11,   11,   11,   11,    0,
       15,    0,   16,   14,    8,    0,    0,    6,    0,    6,
        6,    7,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   12,   10,   10,   10,

       11,    0,    0,    6,    6,    0,   17,    6,    6,   22,
       21,    0,    0,    0,    0,   30,    0,    0,    0,    0,
        0,    0,    0,   20,    0,    0,   20,    0,    0,    0,
       10,   10,   10,   10,    0,   18,    0,   19,   17,    6,
       25,    0,    0,   28,    0,    0,    0,   27,    0,    0,
        0,   20,    0,    0,    0,   20,    0,    0,    0,   10,
       18,   19,    0,    0,    0,    0,    0,    0,    0,   29,
        0,    0,    0,    0,    0,    0,    0,   24,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   23,
        0,    0,    0,    0,    0,    0,    0,   36,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,   35,    0,
        0,   20,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    5,    0,    0,    0,   32,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   31,    0,
        0,   34,    0,    0,    0,    0,    0,    0,    0,   33,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   18,   18,   18,   19,   20,    1,   21,    1,
       22,    1,   23,    1,   24,   24,   24,   24,   25,   26,
       27,   27,   27,   27,   27,   28,   27,   27,   27,   29,
       27,   27,   30,   27,   31,   27,   27,   32,   27,   27,
       33,   34,   35,    1,   36,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   27,   46,   47,   48,   49,
       50,   51,   27,   52,   53,   54,   55,   56,   27,   57,
       58,   27,   59,    1,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    1,    5,    1,
        5,    6,    1,    7,    7,    7,    7,    7,    8,    8,
        1,    1,    3,    9,   10,   11,   12,   13,   12,   12,
       14,   12,    1,    3,    1,   12,   15,   15,    9,    9,
       10,   16,   12,   12,   12,   12,   13,   12,   17,   12,
       12,   17,   12,   17,   14,   17,   17,   12,    1,    1
    } ;

static const flex_int16_t yy_base[385] =
    {   0,
        0,    0,  946, 1139,  942, 1139,   57,  909, 1139, 1139,
     1139,   87,   48,   61,  131,  177, 1139, 1139,   66,   33,
       71, 1139, 1139,  890,  900,   71,  891,  870,  878,  876,
      868,   26,  860,   74, 1139, 1139,  898,   79,  124,  229,
       76,   80,  865,  273,   86,  885,  317, 1139,    0,   97,
       67,  128,  120,   54,   61,  875,  126,    0,  143,   72,
      129,   86,  834,  821,  822,  818,  823,  806, 1139, 1139,
     1139,  794,  791,  795,  795,  781,  781,  793,  791,  793,
      772,  809,  131,  207,  130,  807,  738,  163,  132,  278,
      166,    0, 1139,  243,    0,  149,  198,  169,  149,  178,

        0,  172,  209,  242,  189,  176,  121, 1139,    0,  219,
     1139,  299,  280,  144, 1139,  758,  738,    0,  326,  198,
     1139,  755,  735,  737,  731,  738,  733,  731,  719,  722,
      729, 1139,  722,  717,  716,  721,  714,  704,  307,  186,
      321,  351,  704,  368,  405,  373,  443, 1139,  398,    0,
      210, 1139,  728,  708,  409,  219, 1139,  723,  702,  378,
      407,  456,  408, 1139, 1139,  225,  251,  244,  240,  251,
      315, 1139,  693,  705,  692,  702,  698,  699,  687,  682,
      687,  681,  677,  676,  680,  673,  367,  474,    0,  723,
      461,  689,  234,    0,  488,  518, 1139,  298,  256,  463,

     1139,  298,  339,  308, 1139,  497,  498,  697,  676, 1139,
     1139,  681,  672,  668,  665, 1139,  663,  656,  663,  654,
      659,  669,  652,  544,  549,  596,  574,  284,  346,    0,
      344, 1139,  674,  651,  570,  554,  625,  581, 1139, 1139,
     1139,  643,  646, 1139,  654,  649,  643, 1139,  655,  639,
      642,  622,  407,  462,    0,  644,  475,  678,  434, 1139,
     1139, 1139,  645,  625,  642,  622,  625,  621,  630,  617,
      493,  627,  696,  611,  608,  617,  594, 1139,  615,  576,
      618,  517,  495,  645,  515,    0,  582,  579,  568, 1139,
      578,  567,    0,  650,  651,  750,  563, 1139,  563,  553,

      551,  585,  557,  558,  556,  535,  532,  529, 1139,  532,
      556,  687,  464,  496,  499,  497,  475,  483,  480,  465,
      447,  438,  447,  407, 1139,  408,  396,  389,  391,  377,
      372,  371,  357,  359,  329,  320,  312,  315, 1139,  293,
      268, 1139,  258,  224,  203,  176,  144,  109,   19, 1139,
     1139,  792,  809,  824,  841,  852,  866,  878,  884,  887,
      903,  914,  924,  938,  949,  961,  965,  967,  977,  991,
     1002, 1012, 1022, 1034, 1036, 1048, 1052, 1054, 1064, 1074,
     1090, 1101, 1109, 1121
    } ;

static const flex_int16_t yy_def[385] =
    {   0,
      351,    1,  351,  351,  351,  351,  352,  353,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  352,  351,  351,
      353,  354,  355,  351,  356,  351,  351,  351,  357,   47,
       15,  358,  359,  351,  351,  360,  351,   16,  351,  351,
      351,  352,  353,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  352,  351,  361,  351,  351,  351,  352,  352,
      352,  362,  351,  353,  363,  355,  364,   44,  351,  351,

      365,  351,  356,  351,  351,  351,  366,  351,  357,  367,
      351,  351,  368,  351,  351,  351,  351,  369,  360,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  352,  361,
      351,  370,  351,  352,  352,  353,  353,  351,  355,  371,
      351,  351,  351,  351,  365,  351,  351,  351,  351,  351,
      372,  351,  373,  351,  351,  369,  369,  351,  374,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  352,  361,  375,  351,
      352,  145,  353,  147,  355,  355,  351,  351,  351,  351,

      351,  376,  377,  351,  351,  351,  378,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  361,  361,  351,  145,  355,  196,
      351,  351,  351,  351,  351,  379,  351,  380,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  361,  226,  351,  381,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      381,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  381,  381,  381,  381,  382,  351,  351,  351,  351,
      351,  351,  383,  381,  381,  381,  351,  351,  351,  351,

      351,  384,  381,  381,  296,  351,  351,  351,  351,  351,
      384,  351,  296,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
        0,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351
    } ;

static const flex_int16_t yy_nxt[1200] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    4,    4,   11,
       12,   13,   14,   15,   16,   16,   16,   16,   16,   16,
       17,   18,    4,    4,    4,    4,    4,   19,    4,   20,
       21,    4,   22,    4,   23,    4,   24,   25,   26,   27,
       28,    4,    4,    4,   29,    4,    4,    4,    4,    4,
       30,   31,   32,   33,   34,    4,    4,    4,   35,   36,
       39,   47,   47,   47,   47,   47,   47,   47,   48,   62,
       63,   65,  350,   49,   62,   63,   79,   62,   63,   80,
       93,  114,   39,   66,  115,   69,   70,   71,  116,   39,
       40,   43,   82,   94,   94,   94,   94,   94,  351,  122,

       44,   45,   45,   45,   45,   45,   45,  117,  115,   42,
       64,   72,   40,  104,   46,   83,  105,   46,  123,   40,
       73,  110,  111,  351,  111,   84,   84,   85,  112,  160,
      112,  160,  106,  141,   39,   39,   95,  110,  111,   50,
      105,   46,   50,  111,   51,   51,   51,   51,   51,   52,
       52,   86,   53,  148,   86,   53,  115,  349,   54,  121,
       87,   55,   56,  142,   40,   40,   85,   83,   53,   39,
      120,   53,  114,  121,  115,  120,  151,   57,   88,  152,
      115,   86,   97,  121,  348,   55,  139,   56,   50,  141,
       58,   58,   58,   58,   58,   58,   58,  121,  115,   40,

      351,   53,  152,  152,   59,  153,  157,   60,   84,   84,
       85,  149,  149,  149,  149,  149,  158,   53,  151,  142,
      347,  139,  156,   61,  154,  351,  152,  162,  121,  162,
      157,   60,   89,   89,   86,  159,  104,   86,   93,  105,
      152,  346,   90,   90,   90,   90,   90,   93,  206,  157,
      206,   89,  121,  202,  150,  106,  146,  146,  146,  146,
      146,   88,   89,  105,  152,   91,   89,   42,  345,  156,
       89,  204,  157,  157,  205,  202,   42,   89,  208,  203,
       89,   39,   89,  233,   89,   92,   98,   98,   98,   98,
       98,  144,  144,  144,  144,  144,  157,  209,  205,  344,

       99,  203,  234,  100,  101,  164,  235,  164,  235,  343,
       39,   40,  113,  113,  113,  113,  113,  113,  113,  102,
      228,  164,   84,   84,   85,  231,  164,  100,  232,  101,
       47,   47,   47,   47,   47,   47,   47,  167,  205,  139,
       40,  107,  108,   83,  108,  205,  342,  237,   86,  237,
      148,   86,  232,  168,  169,  341,  170,  107,  108,  187,
      340,  204,  205,  108,  188,  188,  188,  188,  188,  205,
      224,   39,  171,  339,  232,   88,  169,   93,  338,   97,
      170,  191,  191,  191,  191,  191,  193,  193,  193,  193,
      193,  161,  161,  161,  161,  161,  161,  161,  232,  337,

       40,   40,  148,   83,   83,  336,   42,  189,   39,  335,
       62,  195,  195,  195,  195,  195,  334,  333,  192,  192,
      192,  192,  192,  192,  192,   82,  332,  331,  192,  192,
      192,   97,  108,  111,  108,  111,  198,  257,   40,  199,
      330,  192,  192,  192,  192,  192,  192,   93,  108,  111,
      329,  328,  258,  108,  111,  200,  194,  194,  194,  194,
      194,  194,  194,  199,   39,  141,  194,  194,  194,  163,
      163,  163,  163,  163,  163,  163,   42,  141,  272,  194,
      194,  194,  194,  194,  194,  327,  326,  225,  225,  225,
      225,  225,  148,  232,   40,  142,  272,   83,  272,  325,

      313,  229,  229,  229,  229,  229,  324,  142,  273,  231,
      207,  207,  207,  207,  207,  207,  207,  232,  272,  294,
      272,   97,  148,  239,  323,  239,  273,  322,  273,  282,
      321,  230,  230,  230,  230,  230,  230,  230,  320,  239,
      319,  230,  230,  230,  239,  252,  252,   62,  273,  318,
      273,   97,  141,  282,  230,  230,  230,  230,  230,  230,
      312,  272,  254,  254,  254,  254,  254,  310,  317,  316,
      294,   82,  294,  315,   82,  256,  256,  257,  314,  261,
       87,  261,  142,  236,  236,  236,  236,  236,  236,  236,
      273,  273,  313,  282,  282,  261,  310,  309,  253,  141,

      261,  258,  308,  307,  258,  306,  262,  301,  262,  255,
      255,  255,  255,  255,  255,  255,  300,  299,  298,  255,
      255,  255,  262,  252,  252,   62,  297,  262,  259,  142,
      293,  292,  255,  255,  255,  255,  255,  255,  238,  238,
      238,  238,  238,  238,  238,  256,  256,  257,  272,   82,
      291,  290,   82,  272,  272,  289,  288,  287,  295,  295,
      295,  295,  295,   87,  304,  304,  304,  304,  304,  281,
      280,  258,  279,  278,  258,  277,  253,  276,  273,  275,
      274,  257,  270,  273,  273,  269,  282,  282,  256,  256,
      257,  268,  267,  266,  265,  264,  263,  260,  259,  283,

      283,  260,  303,  251,  250,  249,  248,  247,  246,  284,
      284,  284,  284,  284,  258,  245,  244,  258,  283,  243,
      242,  241,  240,   87,  240,  228,  227,  223,  222,  283,
      221,  220,  285,  283,  219,  218,  217,  283,  216,  215,
      214,  259,  213,  212,  283,  211,  210,  283,  201,  283,
      201,  283,  286,  272,  197,  197,  190,  186,  185,  184,
      183,  182,  181,  305,  305,  305,  305,  305,  305,  305,
      180,  179,  178,  305,  305,  305,  177,  176,  175,  174,
      173,  172,  172,  273,  165,  165,  305,  305,  305,  305,
      305,  305,   38,  143,   38,   38,   38,   38,   38,   38,

       38,   38,   38,   38,   38,   38,   38,   38,   38,   41,
       85,   41,   62,   41,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   41,   41,   41,  138,  137,
       41,  136,  135,  134,  133,  132,  131,  130,   41,   41,
       41,   96,  129,   96,  128,   96,   96,   96,   96,   96,
       96,   96,   96,   96,   96,   96,   96,   96,  103,  103,
      127,  126,  125,  124,  103,  103,  109,   42,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,   52,   52,   52,  118,   52,  113,   43,
      113,  113,  119,  119,  119,  119,  119,  119,   97,   37,

       81,  119,  119,  140,   78,  140,  140,  140,  140,  140,
      140,  140,  140,  140,  140,  140,  140,  140,  140,  140,
      145,  145,  145,  145,  145,   77,   76,   75,  145,  145,
      147,  147,  147,  147,  147,   74,   68,   67,  147,  147,
       96,   96,   42,   37,   96,  351,  351,  351,  351,  351,
      351,  351,   96,   96,   96,  155,  155,  155,  155,  155,
      351,  351,  351,  155,  155,  161,  351,  161,  161,  163,
      351,  163,  163,  113,  113,  351,  351,  113,  351,  113,
      351,  351,  113,  166,  166,  166,  166,  166,  351,  351,
      351,  166,  166,  140,  140,  351,  351,  140,  351,  351,

      351,  351,  351,  351,  351,  140,  140,  140,  196,  196,
      196,  196,  196,  351,  351,  351,  196,  196,  161,  161,
      351,  351,  161,  351,  161,  351,  351,  161,  163,  163,
      351,  351,  163,  351,  163,  351,  351,  163,  207,  351,
      207,  207,  226,  226,  226,  226,  226,  351,  351,  351,
      226,  226,  236,  351,  236,  236,  238,  351,  238,  238,
      207,  207,  351,  351,  207,  351,  207,  351,  351,  207,
      236,  236,  351,  351,  236,  351,  236,  351,  351,  236,
      238,  238,  351,  351,  238,  351,  238,  351,  351,  238,
      271,  351,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  296,  296,  296,
      296,  296,  351,  351,  351,  296,  296,  302,  302,  302,
      302,  302,  302,  302,  302,  302,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  311,    3,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351

    } ;

static const flex_int16_t yy_chk[1200] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        7,   13,   13,   13,   13,   13,   13,   13,   14,   19,
       19,   20,  349,   14,   21,   21,   32,   34,   34,   32,
       41,   54,   38,   20,   54,   26,   26,   26,   55,   62,
        7,   12,   34,   42,   42,   42,   42,   42,   51,   60,

       12,   12,   12,   12,   12,   12,   12,   55,   54,   41,
       19,   26,   38,   45,   12,   38,   45,   12,   60,   62,
       26,   50,   50,   51,   50,   39,   39,   39,   53,  107,
       53,  107,   45,   85,   83,   89,   42,   50,   50,   52,
       45,   12,   15,   50,   15,   15,   15,   15,   15,   15,
       15,   39,   52,   96,   39,   15,   57,  348,   15,   61,
       39,   15,   15,   85,   83,   89,   88,   83,   52,   91,
       59,   15,   57,   59,  114,   61,   99,   15,   39,   99,
       57,   88,   96,   61,  347,   15,   83,   15,   16,  140,
       16,   16,   16,   16,   16,   16,   16,   59,  114,   91,

       98,   16,  102,   99,   16,  100,  106,   16,   84,   84,
       84,   97,   97,   97,   97,   97,  105,   16,  102,  140,
      346,   91,  106,   16,  100,   98,  102,  110,  120,  110,
      106,   16,   40,   40,   84,  105,  103,   84,  193,  103,
      151,  345,   40,   40,   40,   40,   40,   94,  169,  156,
      169,   40,  120,  166,   97,  103,   94,   94,   94,   94,
       94,   84,   40,  103,  151,   40,   40,  193,  344,  104,
       40,  168,  104,  156,  168,  166,   94,   40,  170,  167,
       40,   90,   40,  199,   40,   40,   44,   44,   44,   44,
       44,   90,   90,   90,   90,   90,  104,  170,  168,  343,

       44,  167,  199,   44,   44,  113,  202,  113,  202,  341,
      139,   90,  112,  112,  112,  112,  112,  112,  112,   44,
      228,  113,  141,  141,  141,  198,  113,   44,  198,   44,
       47,   47,   47,   47,   47,   47,   47,  119,  204,  228,
      139,   47,   47,  139,   47,  171,  340,  203,  141,  203,
      229,  141,  198,  119,  119,  338,  119,   47,   47,  139,
      337,  171,  204,   47,  142,  142,  142,  142,  142,  171,
      187,  144,  119,  336,  231,  141,  119,  146,  335,  229,
      119,  144,  144,  144,  144,  144,  146,  146,  146,  146,
      146,  160,  160,  160,  160,  160,  160,  160,  231,  334,

      187,  144,  149,  187,  144,  333,  146,  142,  145,  332,
      253,  149,  149,  149,  149,  149,  331,  330,  145,  145,
      145,  145,  145,  145,  145,  253,  329,  328,  145,  145,
      145,  149,  161,  163,  161,  163,  155,  259,  145,  155,
      327,  145,  145,  145,  145,  145,  145,  147,  161,  163,
      326,  324,  259,  161,  163,  155,  147,  147,  147,  147,
      147,  147,  147,  155,  191,  254,  147,  147,  147,  162,
      162,  162,  162,  162,  162,  162,  147,  188,  257,  147,
      147,  147,  147,  147,  147,  323,  322,  188,  188,  188,
      188,  188,  195,  200,  191,  254,  271,  191,  283,  321,

      313,  195,  195,  195,  195,  195,  320,  188,  257,  200,
      206,  206,  206,  206,  206,  206,  206,  200,  285,  313,
      282,  195,  196,  207,  319,  207,  271,  318,  283,  271,
      317,  196,  196,  196,  196,  196,  196,  196,  316,  207,
      315,  196,  196,  196,  207,  224,  224,  224,  285,  314,
      282,  196,  225,  282,  196,  196,  196,  196,  196,  196,
      303,  304,  225,  225,  225,  225,  225,  311,  310,  308,
      285,  224,  282,  307,  224,  227,  227,  227,  306,  236,
      224,  236,  225,  235,  235,  235,  235,  235,  235,  235,
      303,  304,  305,  303,  304,  236,  302,  301,  224,  226,

      236,  227,  300,  299,  227,  297,  238,  292,  238,  226,
      226,  226,  226,  226,  226,  226,  291,  289,  288,  226,
      226,  226,  238,  252,  252,  252,  287,  238,  227,  226,
      281,  280,  226,  226,  226,  226,  226,  226,  237,  237,
      237,  237,  237,  237,  237,  256,  256,  256,  284,  252,
      279,  277,  252,  294,  295,  276,  275,  274,  284,  284,
      284,  284,  284,  272,  295,  295,  295,  295,  295,  270,
      269,  256,  268,  267,  256,  266,  252,  265,  284,  264,
      263,  258,  251,  294,  295,  250,  294,  295,  312,  312,
      312,  249,  247,  246,  245,  243,  242,  234,  256,  273,

      273,  233,  294,  223,  222,  221,  220,  219,  218,  273,
      273,  273,  273,  273,  312,  217,  215,  312,  273,  214,
      213,  212,  209,  312,  208,  192,  190,  186,  185,  273,
      184,  183,  273,  273,  182,  181,  180,  273,  179,  178,
      177,  312,  176,  175,  273,  174,  173,  273,  159,  273,
      158,  273,  273,  296,  154,  153,  143,  138,  137,  136,
      135,  134,  133,  296,  296,  296,  296,  296,  296,  296,
      131,  130,  129,  296,  296,  296,  128,  127,  126,  125,
      124,  123,  122,  296,  117,  116,  296,  296,  296,  296,
      296,  296,  352,   87,  352,  352,  352,  352,  352,  352,

      352,  352,  352,  352,  352,  352,  352,  352,  352,  353,
       86,  353,   82,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  354,  354,   81,   80,
      354,   79,   78,   77,   76,   75,   74,   73,  354,  354,
      354,  355,   72,  355,   68,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  356,  356,
       67,   66,   65,   64,  356,  356,  357,   63,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  358,  358,  358,   56,  358,  359,   46,
      359,  359,  360,  360,  360,  360,  360,  360,   43,   37,

       33,  360,  360,  361,   31,  361,  361,  361,  361,  361,
      361,  361,  361,  361,  361,  361,  361,  361,  361,  361,
      362,  362,  362,  362,  362,   30,   29,   28,  362,  362,
      363,  363,  363,  363,  363,   27,   25,   24,  363,  363,
      364,  364,    8,    5,  364,    3,    0,    0,    0,    0,
        0,    0,  364,  364,  364,  365,  365,  365,  365,  365,
        0,    0,    0,  365,  365,  366,    0,  366,  366,  367,
        0,  367,  367,  368,  368,    0,    0,  368,    0,  368,
        0,    0,  368,  369,  369,  369,  369,  369,    0,    0,
        0,  369,  369,  370,  370,    0,    0,  370,    0,    0,

        0,    0,    0,    0,    0,  370,  370,  370,  371,  371,
      371,  371,  371,    0,    0,    0,  371,  371,  372,  372,
        0,    0,  372,    0,  372,    0,    0,  372,  373,  373,
        0,    0,  373,    0,  373,    0,    0,  373,  374,    0,
      374,  374,  375,  375,  375,  375,  375,    0,    0,    0,
      375,  375,  376,    0,  376,  376,  377,    0,  377,  377,
      378,  378,    0,    0,  378,    0,  378,    0,    0,  378,
      379,  379,    0,    0,  379,    0,  379,    0,    0,  379,
      380,  380,    0,    0,  380,    0,  380,    0,    0,  380,
      381,    0,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  382,  382,  382,
      382,  382,    0,    0,    0,  382,  382,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  384,  384,  384,  384,
      384,  384,  384,  384,  384,  384,  384,  384,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  351,  351

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[53] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.l"
#line 29 "flex.l"

	#include "y.tab.h"
	#define MAXLEN 100

#define CNRM  "\x1B[0m"
#define CRED  "\x1B[31;1m"
#define CGRN  "\x1B[32;1m"
#define CYEL  "\x1B[33m"
#define CBLU  "\x1B[34m"
#define CMAG  "\x1B[35m"
#define CCYN  "\x1B[36m"
#define CWHT  "\x1B[0m"
#define CWHTN  "\x1B[1m"

extern void yyerror(const char *);  /* prints grammar violation message */
static void comment(void);
void count(void);


int previousColumn = 0;
int column = 0;
int cursorPos = 0;

#line 881 "lex.yy.c"
/*Taken from https://www.lysator.liu.se/c/ANSI-C-grammar-l.html*/
#line 883 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 56 "flex.l"

#line 1102 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 352 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1139 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "flex.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "flex.l"
{ column = 0; /* consume //-comment */ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 59 "flex.l"
{/*yylineno = ++lineNum;*/}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "flex.l"
{/*DO NOTHING*/}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "flex.l"
{ return TEXTURE_FILE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "flex.l"
{  return F_CONSTANT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "flex.l"
{  return F_CONSTANT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "flex.l"
{  return F_CONSTANT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "flex.l"
{  return F_CONSTANT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "flex.l"
{  return F_CONSTANT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "flex.l"
{ return F_CONSTANT; }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 83 "flex.l"
{ return STRING_LITERAL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 85 "flex.l"
{ return SCENE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 86 "flex.l"
{ return LIGHT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 87 "flex.l"
{ return INTENSITY; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "flex.l"
{ return POSITION; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 89 "flex.l"
{ return SPHERE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 90 "flex.l"
{ return EYE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 91 "flex.l"
{ return RADIUS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 92 "flex.l"
{ return CENTER; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 93 "flex.l"
{ return TEXTURE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 94 "flex.l"
{return COLOR; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 95 "flex.l"
{return DIFFUSE_COEFFICIENT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "flex.l"
{ return AMBIENT_LIGHTING; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 97 "flex.l"
{	return AMBIENT_LIGHTING_COEFFICIENT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 98 "flex.l"
{ return SPECULAR_COEFFICIENT; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 99 "flex.l"
{ return STAIN_LEVEL_KN; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 100 "flex.l"
{ return BACKGROUND; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 101 "flex.l"
{ return LIGHT_C1; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 102 "flex.l"
{ return LIGHT_C2; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 103 "flex.l"
{ return LIGHT_C3; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 104 "flex.l"
{ return '='; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 105 "flex.l"
{ return ';'; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 106 "flex.l"
{ return ','; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 107 "flex.l"
{ return '('; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 108 "flex.l"
{ return ')'; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 109 "flex.l"
{ return '{'; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 110 "flex.l"
{ return '}'; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 111 "flex.l"
{ return '['; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 112 "flex.l"
{ return ']'; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 114 "flex.l"
{ }
	YY_BREAK
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 116 "flex.l"
{ yyerror("SHOULD HAVE EXTENSION .avs"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 117 "flex.l"
{ yyerror("LEXICAL ERROR"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 118 "flex.l"
ECHO;
	YY_BREAK
#line 1432 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 352 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 352 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 351);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 118 "flex.l"



void yyerror(const char *s)
{
	printf("%sError%s in line %d: %s\n", CRED, CWHT, yylineno , s);
	exit(1);
}
static void comment(void)
{
	int c;

	while ((c = input()) != EOF)
	{
		cursorPos++;
		if (c == '*')
		{
			while ((c = input()) == '*')
			{
				cursorPos++;
			}

			cursorPos++;
			if (c == '/')
				return;

			if (c == EOF)
				break;
		}
	}
}


void count(void)
{
	previousColumn = column;

	int i;
	for (i = 0; yytext[i] != '\0'; i++)
	{
		if (yytext[i] == '\n')
			column = 0;
		else
			column++;

		cursorPos++;
	}

	//ECHO;
}



