
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 46
#define YY_END_OF_BUFFER 47
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[309] =
    {   0,
        0,    0,   47,   45,    4,    3,   45,   45,   37,   38,
       36,   45,   45,   45,    8,    7,   35,   34,   45,   45,
       45,   41,   42,   45,   45,   45,   45,   45,   45,   45,
       45,   45,   39,   40,   43,    0,   44,    0,    0,    0,
        0,   12,   11,    0,   15,    1,    2,   16,    8,    0,
        0,    8,    8,    0,    8,    7,    7,    7,    7,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   44,    0,    0,    0,    0,
        0,    0,    0,    0,    9,    0,    0,    0,    0,   12,
       12,   12,    0,   12,   11,   11,   11,   11,    0,   15,

        2,    0,   16,    0,   14,    8,    8,    8,    8,    0,
        6,    7,    7,    7,    7,    0,    0,    0,    0,    0,
        0,    0,   26,    0,    0,    0,    0,    0,    0,   44,
        0,    0,    0,    0,    0,    0,   13,    0,    0,   12,
       12,   12,   12,   10,   11,   11,   11,   11,    0,   15,
        0,   16,   14,    8,    0,    0,    6,    0,    6,    6,
        7,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   12,   10,   10,   10,   11,    0,    0,    6,
        6,    0,   17,    6,    6,   22,   21,    0,    0,    0,

       30,    0,    0,    0,    0,    0,   20,    0,    0,   20,
        0,    0,    0,   10,   10,   10,   10,    0,   18,    0,
       19,   17,    6,   25,    0,   28,    0,    0,    0,   27,
        0,   20,    0,    0,    0,   20,    0,    0,    0,   10,
       18,   19,    0,    0,    0,    0,   29,    0,    0,    0,
        0,    0,    0,   24,    0,    0,    0,    0,    0,    0,
        0,    0,   23,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   20,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    5,    0,    0,
       32,    0,    0,    0,    0,    0,    0,   31,    0,    0,

        0,    0,    0,    0,    0,    0,   33,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   16,   17,    1,   18,    1,
       19,    1,   20,    1,   21,   21,   21,   21,   22,   23,
       24,   24,   24,   24,   24,   25,   24,   24,   24,   26,
       24,   24,   27,   24,   28,   24,   24,   29,   24,   24,
       30,   31,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   24,   24,   43,   44,   45,
       46,   47,   24,   48,   49,   50,   51,   52,   24,   53,
       54,   24,   55,    1,   56,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[57] =
    {   0,
        1,    1,    2,    3,    4,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    6,    7,    7,    1,    1,    3,
        8,    8,    8,    9,    9,    9,    9,    9,    9,    1,
        3,    1,    9,   10,   10,    8,    8,    8,   10,    9,
        9,    9,    9,    9,   11,    9,    9,   11,    9,   11,
        9,   11,   11,    9,    1,    1
    } ;

static const flex_int16_t yy_base[330] =
    {   0,
        0,    0,  763,  885,  757,  885,   53,  727,  885,  885,
      885,   53,   45,   58,   93,  135,  885,  885,   59,   29,
       68,  885,  885,  713,   36,  713,  696,  704,  702,  712,
      698,   75,  885,  885,  732,   82,   86,   85,   72,   79,
      692,  139,  155,  715,  193,  885,    0,  223,   73,  179,
      188,  105,   81,  707,   84,    0,  114,   98,   97,  124,
      687,  677,  678,  674,  679,  668,  669,  672,  672,  659,
      659,  670,  653,  701,  216,  224,  130,  699,  650,   71,
      154,  210,  225,    0,  885,  228,    0,  112,  160,  239,
      230,  134,    0,  138,  255,  235,  187,  245,  278,  885,

        0,  288,  885,   81,  293,  160,  885,  676,  657,    0,
      299,  172,  885,  674,  654,  655,  649,  649,  644,  634,
      637,  643,  885,  643,  638,  637,  628,  281,  247,  319,
      286,  618,  334,  367,  314,  402,  885,  326,    0,  193,
      885,  641,  622,  292,  206,  885,  639,  620,  337,  428,
      344,  433,  885,  885,  287,  329,  341,  363,  342,  369,
      885,  612,  623,  612,  621,  618,  607,  602,  606,  595,
      593,  590,  360,  395,    0,  635,  396,  602,  260,    0,
      447,  474,  885,  383,  350,  403,  885,  466,  505,  286,
      885,  449,  509,  610,  591,  885,  885,  594,  586,  580,

      885,  574,  571,  577,  569,  565,  525,  455,  573,  490,
      361,  391,    0,  305,  885,  581,  542,  484,  521,  540,
      558,  885,  885,  885,  534,  885,  544,  538,  532,  885,
      533,  589,  469,  383,    0,  596,  424,  566,  526,  885,
      885,  885,  536,  535,  515,  517,  502,  453,  515,  552,
      504,  507,  486,  885,  526,  527,  502,  611,  598,    0,
      475,  461,  885,    0,  599,  623,  654,  464,  465,  490,
      612,  618,  440,  427,  421,  401,  420,  670,  511,  379,
      382,  363,  344,  331,  314,  317,  290,  885,  244,  237,
      243,  236,  199,  177,  173,  137,  146,  885,  140,  137,

      120,  109,   87,   54,   40,   33,  885,  885,  721,  732,
      741,  750,  761,  772,  779,  789,  795,  800,  808,  814,
      819,  827,  833,  838,  848,  857,  863,  866,  873
    } ;

static const flex_int16_t yy_def[330] =
    {   0,
      308,    1,  308,  308,  308,  308,  309,  310,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  309,  308,  311,  310,  312,
      313,  308,  308,  308,  308,  308,  314,  308,   15,  308,
      308,  308,  308,  315,  308,   16,  308,  308,  308,  309,
      310,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  309,  308,  316,  308,  308,  308,
      309,  309,  309,  317,  308,  310,  318,  313,  319,  308,
      308,  308,  320,  308,  308,  308,  308,  308,  308,  308,

      314,  308,  308,  308,  308,  308,  308,  308,  308,  321,
      315,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  309,  316,  308,
      322,  308,  309,  309,  310,  310,  308,  313,  323,  308,
      308,  308,  308,  320,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  321,  321,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  309,  316,  324,  308,  309,  134,  310,  136,
      313,  313,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  316,  316,  308,
      134,  313,  182,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  316,  209,  308,  325,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  325,  308,  326,
      308,  308,  308,  308,  308,  325,  325,  325,  325,  327,
      308,  308,  308,  328,  325,  325,  325,  308,  308,  329,
      325,  325,  267,  308,  308,  308,  329,  308,  267,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,    0,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308
    } ;

static const flex_int16_t yy_nxt[942] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,    4,    4,   11,
       12,   13,   14,   15,   16,   16,   16,   17,   18,    4,
        4,    4,    4,    4,   19,    4,   20,   21,    4,   22,
        4,   23,    4,   24,    4,   25,   26,   27,    4,    4,
        4,   28,    4,    4,    4,    4,   29,   30,    4,   31,
       32,    4,    4,    4,   33,   34,   37,   41,   45,   45,
       45,   45,   60,   61,   63,   46,   42,   43,   43,   43,
       47,   60,   61,   66,   77,   64,   85,   44,   60,   61,
       44,   67,  307,   38,  306,   37,   78,   76,   76,   77,
       74,  305,   86,   86,  105,  105,  105,  105,   82,   82,

       62,  308,   40,   44,   48,  108,   49,   49,   50,   50,
       78,  107,   38,   78,   51,   75,  137,   52,   83,   79,
       53,   54,  114,  109,  113,  308,  106,   37,  304,  106,
       51,   87,  107,  130,  107,   55,   80,   84,  112,  112,
      115,  113,   89,   53,  303,   54,   48,  113,   56,   56,
       56,   56,   90,   90,   38,  107,   51,   37,  142,   57,
      131,  302,   58,   91,  113,  141,   92,   93,   95,   95,
       95,   95,   51,  138,  138,  301,  143,   59,  300,   96,
      140,   94,   97,  299,   38,   58,  298,  107,  141,   92,
       48,   93,   50,   50,   50,   50,  104,   98,  104,  113,

       51,  105,  105,  105,  105,   97,   45,   45,   45,   45,
      107,  147,  139,   37,   99,  100,   51,  100,  297,   37,
      141,  296,  113,  133,  133,   76,   76,   77,   37,  148,
       99,  100,   85,  146,  295,  100,   45,   45,   45,   45,
       38,  135,  135,  141,  102,  103,   38,  103,   78,   75,
      130,   78,   90,   90,  140,   38,  146,  141,   40,  145,
      102,  103,  146,   91,   85,  103,   92,  128,   95,   95,
       95,   95,  146,  294,   80,  293,  128,  131,  292,   96,
      141,   94,   97,  291,   37,  146,  149,  145,  149,   92,
       40,  150,  150,  150,  150,  146,  151,   98,  151,  174,

      174,  152,  152,  152,  152,   97,  105,  105,  105,  105,
      156,   38,  188,  191,   75,  153,  184,  153,   85,  185,
       76,   76,   77,  157,  158,  290,  159,  179,  179,  173,
      137,  153,  215,  188,  186,  153,  191,   37,  175,  181,
      181,  160,  185,   78,   40,  158,   78,  177,  177,  159,
      150,  150,  150,  150,  189,  215,   89,  152,  152,  152,
      152,  289,  288,  207,   38,  190,  194,   75,  191,   80,
       37,  192,  287,  192,  216,  189,  193,  193,  193,  193,
      178,  178,  178,  178,  195,  286,  130,  178,  178,  178,
       38,  191,  217,   75,  211,  137,  191,   38,  130,   37,

      178,  178,  178,  178,  178,  178,   85,  214,  208,  208,
      215,  190,  128,  131,  285,  180,  180,  180,  180,  191,
      284,   89,  180,  180,  180,  131,   38,  249,  283,   75,
      215,  276,   40,  215,  282,  180,  180,  180,  180,  180,
      180,  150,  150,  150,  150,  214,  152,  152,  152,  152,
      100,  137,  100,  215,  250,  103,  249,  103,  130,  281,
      212,  212,  193,  193,  193,  193,  100,  280,  234,  234,
      100,  103,   60,  279,  218,  103,  218,   89,  137,  219,
      219,  219,  219,  250,   74,  131,  256,  213,  213,  213,
      213,  236,  236,  237,  213,  213,  213,  219,  219,  219,

      219,  276,  275,  274,   89,  249,  269,  213,  213,  213,
      213,  213,  213,  220,  238,  220,  268,  238,  221,  221,
      221,  221,  193,  193,  193,  193,  232,  232,   60,  237,
      249,  222,  250,  222,  219,  219,  219,  219,  264,  263,
      239,  238,  262,  241,  279,  241,  261,  222,   79,   74,
      255,  222,   74,  221,  221,  221,  221,  250,   79,  241,
      256,  254,  265,  241,  253,  258,  258,  252,  251,  237,
      247,  221,  221,  221,  221,  233,  130,  246,  265,  245,
      242,  244,  242,  243,  240,  259,  235,  235,  235,  235,
      232,  232,   60,  235,  235,  235,  242,  236,  236,  237,

      242,  249,  249,  131,  260,  240,  235,  235,  235,  235,
      235,  235,  231,   74,  249,  278,   74,  230,  229,  228,
      238,  249,  227,  238,  266,  266,  249,  226,  250,  250,
      225,  224,  256,  223,  223,  211,  272,  272,  210,  233,
      206,  250,  250,  205,  204,  256,  239,  271,  250,  265,
      203,  256,  202,  250,  201,  200,  256,  249,  199,  198,
      197,  196,  187,  187,  183,  183,  176,  273,  273,  273,
      273,  236,  236,  237,  273,  273,  273,  172,  171,  170,
      169,  168,  167,  166,  250,  165,  164,  273,  273,  273,
      273,  273,  273,  163,  238,  162,  161,  238,  161,  154,

      154,  132,   77,   79,   60,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  118,  117,  116,   40,  110,   41,
      239,   36,   89,   36,   36,   36,   36,   36,   36,   36,
       36,   36,   39,   35,   39,   73,   39,   39,   39,   39,
       39,   39,   39,   81,   81,   72,   81,   71,   70,   69,
       81,   81,   39,   39,   68,   39,   65,   40,   35,   39,
       39,   88,  308,   88,  308,   88,   88,   88,   88,   88,
       88,   88,  101,  308,  101,  101,  101,  101,  101,  101,
      101,  101,  101,  111,  111,  111,  111,  308,  111,  129,
      308,  129,  129,  129,  129,  129,  129,  129,  129,  129,

      134,  134,  134,  308,  134,  136,  136,  136,  308,  136,
       88,   88,  308,   88,  308,  308,  308,   88,   88,  144,
      144,  144,  308,  144,  155,  155,  155,  308,  155,  129,
      129,  308,  129,  308,  308,  308,  129,  129,  182,  182,
      182,  308,  182,  209,  209,  209,  308,  209,  248,  308,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  257,
      257,  308,  257,  308,  308,  308,  257,  257,  267,  267,
      267,  308,  267,  270,  270,  270,  270,  277,  277,  277,
      277,  277,  277,  277,    3,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308
    } ;

static const flex_int16_t yy_chk[942] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    7,   12,   13,   13,
       13,   13,   19,   19,   20,   14,   12,   12,   12,   12,
       14,   21,   21,   25,   80,   20,   39,   12,   32,   32,
       12,   25,  306,    7,  305,   36,   80,   37,   37,   37,
       32,  304,   40,   40,  104,  104,  104,  104,   38,   38,

       19,   49,   39,   12,   15,   53,   15,   15,   15,   15,
       37,   55,   36,   37,   15,   36,   88,   15,   38,   37,
       15,   15,   58,   53,   59,   49,   55,   60,  303,   52,
       15,   40,   52,   77,   55,   15,   37,   38,   57,   59,
       58,   57,   88,   15,  302,   15,   16,   59,   16,   16,
       16,   16,   42,   42,   60,   52,   16,   81,   92,   16,
       77,  301,   16,   42,   57,   94,   42,   42,   43,   43,
       43,   43,   16,   89,   89,  300,   92,   16,  299,   43,
       94,   42,   43,  297,   81,   16,  296,  106,   94,   42,
       50,   42,   50,   50,   50,   50,   51,   43,   51,  112,

       50,   51,   51,   51,   51,   43,   45,   45,   45,   45,
      106,   97,   89,   82,   45,   45,   50,   45,  295,   75,
      140,  294,  112,   82,   82,   76,   76,   76,   83,   97,
       45,   45,   86,  145,  293,   45,   48,   48,   48,   48,
       82,   86,   86,  140,   48,   48,   75,   48,   76,   75,
      129,   76,   90,   90,   91,   83,  145,   91,   86,   96,
       48,   48,   96,   90,  179,   48,   90,   75,   95,   95,
       95,   95,   98,  292,   76,  291,   83,  129,  290,   95,
       91,   90,   95,  289,  128,   96,   99,   98,   99,   90,
      179,   99,   99,   99,   99,   98,  102,   95,  102,  131,

      131,  102,  102,  102,  102,   95,  105,  105,  105,  105,
      111,  128,  155,  190,  128,  105,  144,  105,  135,  144,
      130,  130,  130,  111,  111,  287,  111,  135,  135,  128,
      138,  105,  214,  155,  144,  105,  190,  133,  131,  138,
      138,  111,  144,  130,  135,  111,  130,  133,  133,  111,
      149,  149,  149,  149,  156,  214,  138,  151,  151,  151,
      151,  286,  285,  173,  133,  157,  159,  133,  157,  130,
      134,  158,  284,  158,  185,  156,  158,  158,  158,  158,
      134,  134,  134,  134,  159,  283,  234,  134,  134,  134,
      173,  157,  185,  173,  211,  212,  160,  134,  174,  177,

      134,  134,  134,  134,  134,  134,  136,  184,  174,  174,
      184,  160,  211,  234,  282,  136,  136,  136,  136,  160,
      281,  212,  136,  136,  136,  174,  177,  237,  280,  177,
      186,  277,  136,  184,  276,  136,  136,  136,  136,  136,
      136,  150,  150,  150,  150,  186,  152,  152,  152,  152,
      150,  181,  150,  186,  237,  152,  248,  152,  208,  275,
      181,  181,  192,  192,  192,  192,  150,  274,  208,  208,
      150,  152,  233,  273,  188,  152,  188,  181,  182,  188,
      188,  188,  188,  248,  233,  208,  248,  182,  182,  182,
      182,  210,  210,  210,  182,  182,  182,  218,  218,  218,

      218,  270,  269,  268,  182,  257,  262,  182,  182,  182,
      182,  182,  182,  189,  210,  189,  261,  210,  189,  189,
      189,  189,  193,  193,  193,  193,  207,  207,  207,  239,
      256,  193,  257,  193,  219,  219,  219,  219,  255,  253,
      210,  239,  252,  219,  279,  219,  251,  193,  249,  207,
      247,  193,  207,  220,  220,  220,  220,  256,  207,  219,
      256,  246,  279,  219,  245,  250,  250,  244,  243,  238,
      231,  221,  221,  221,  221,  207,  209,  229,  256,  228,
      221,  227,  221,  225,  217,  250,  209,  209,  209,  209,
      232,  232,  232,  209,  209,  209,  221,  236,  236,  236,

      221,  259,  265,  209,  250,  216,  209,  209,  209,  209,
      209,  209,  206,  232,  258,  271,  232,  205,  204,  203,
      236,  272,  202,  236,  258,  258,  266,  200,  259,  265,
      199,  198,  265,  195,  194,  178,  266,  266,  176,  232,
      172,  258,  271,  171,  170,  271,  236,  265,  272,  259,
      169,  272,  168,  266,  167,  166,  266,  267,  165,  164,
      163,  162,  148,  147,  143,  142,  132,  267,  267,  267,
      267,  278,  278,  278,  267,  267,  267,  127,  126,  125,
      124,  122,  121,  120,  267,  119,  118,  267,  267,  267,
      267,  267,  267,  117,  278,  116,  115,  278,  114,  109,

      108,   79,   78,  278,   74,   73,   72,   71,   70,   69,
       68,   67,   66,   65,   64,   63,   62,   61,   54,   44,
      278,  309,   41,  309,  309,  309,  309,  309,  309,  309,
      309,  309,  310,   35,  310,   31,  310,  310,  310,  310,
      310,  310,  310,  311,  311,   30,  311,   29,   28,   27,
      311,  311,  312,  312,   26,  312,   24,    8,    5,  312,
      312,  313,    3,  313,    0,  313,  313,  313,  313,  313,
      313,  313,  314,    0,  314,  314,  314,  314,  314,  314,
      314,  314,  314,  315,  315,  315,  315,    0,  315,  316,
        0,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      317,  317,  317,    0,  317,  318,  318,  318,    0,  318,
      319,  319,    0,  319,    0,    0,    0,  319,  319,  320,
      320,  320,    0,  320,  321,  321,  321,    0,  321,  322,
      322,    0,  322,    0,    0,    0,  322,  322,  323,  323,
      323,    0,  323,  324,  324,  324,    0,  324,  325,    0,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  326,
      326,    0,  326,    0,    0,    0,  326,  326,  327,  327,
      327,    0,  327,  328,  328,  328,  328,  329,  329,  329,
      329,  329,  329,  329,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[47] =
    {   0,
0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "flex.l"
#line 29 "flex.l"

	#include "y.tab.h"
	#define MAXLEN 100

#define CNRM  "\x1B[0m"
#define CRED  "\x1B[31;1m"
#define CGRN  "\x1B[32;1m"
#define CYEL  "\x1B[33m"
#define CBLU  "\x1B[34m"
#define CMAG  "\x1B[35m"
#define CCYN  "\x1B[36m"
#define CWHT  "\x1B[0m"
#define CWHTN  "\x1B[1m"

extern void yyerror(const char *);  /* prints grammar violation message */
static void comment(void);
void count(void);


int previousColumn = 0;
int column = 0;
int cursorPos = 0;

#line 808 "lex.yy.c"
/*Taken from https://www.lysator.liu.se/c/ANSI-C-grammar-l.html*/
#line 810 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 56 "flex.l"

#line 1029 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 309 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 885 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "flex.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "flex.l"
{ column = 0; /* consume //-comment */ }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 59 "flex.l"
{/*yylineno = ++lineNum;*/}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "flex.l"
{/*DO NOTHING*/}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 63 "flex.l"
{ return TEXTURE_FILE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 64 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 65 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 66 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "flex.l"
{  return I_CONSTANT; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 76 "flex.l"
{  return F_CONSTANT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "flex.l"
{  return F_CONSTANT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "flex.l"
{  return F_CONSTANT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "flex.l"
{  return F_CONSTANT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "flex.l"
{  return F_CONSTANT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "flex.l"
{ return F_CONSTANT; }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 83 "flex.l"
{ return STRING_LITERAL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 85 "flex.l"
{ return SCENE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 86 "flex.l"
{ return LIGHT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 87 "flex.l"
{ return INTENSITY; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "flex.l"
{ return POSITION; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 89 "flex.l"
{ return SPHERE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 90 "flex.l"
{ return EYE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 91 "flex.l"
{ return RADIUS; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 92 "flex.l"
{ return CENTER; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 93 "flex.l"
{ return TEXTURE; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 94 "flex.l"
{return COLOR; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 95 "flex.l"
{return DIFFUSE_COEFFICIENT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "flex.l"
{ return AMBIENT_LIGHTING; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 97 "flex.l"
{	return AMBIENT_LIGHTING_COEFFICIENT; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 98 "flex.l"
{ return '='; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 99 "flex.l"
{ return ';'; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 100 "flex.l"
{ return ','; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 101 "flex.l"
{ return '('; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 102 "flex.l"
{ return ')'; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 103 "flex.l"
{ return '{'; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 104 "flex.l"
{ return '}'; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 105 "flex.l"
{ return '['; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 106 "flex.l"
{ return ']'; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 108 "flex.l"
{ }
	YY_BREAK
case 44:
/* rule 44 can match eol */
YY_RULE_SETUP
#line 110 "flex.l"
{ yyerror("SHOULD HAVE EXTENSION .avs"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 111 "flex.l"
{ yyerror("LEXICAL ERROR"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 112 "flex.l"
ECHO;
	YY_BREAK
#line 1329 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 309 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 309 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 308);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 112 "flex.l"



void yyerror(const char *s)
{
	printf("%sError%s in line %d: %s\n", CRED, CWHT, yylineno , s);
	exit(1);
}
static void comment(void)
{
	int c;

	while ((c = input()) != EOF)
	{
		cursorPos++;
		if (c == '*')
		{
			while ((c = input()) == '*')
			{
				cursorPos++;
			}

			cursorPos++;
			if (c == '/')
				return;

			if (c == EOF)
				break;
		}
	}
}


void count(void)
{
	previousColumn = column;

	int i;
	for (i = 0; yytext[i] != '\0'; i++)
	{
		if (yytext[i] == '\n')
			column = 0;
		else
			column++;

		cursorPos++;
	}

	//ECHO;
}



